### PR TITLE
Add blacklist option for paths to Firebase::Client (with spec)

### PR DESCRIPTION
**Pull request by bdsimmons**
See Readme Update for why

### CODE REVIEW

**Comment by vincentwoo** [comment]
Can you explain why you wouldn't just use Firebase security rules?

https://www.firebase.com/docs/security/guide/

**Comment by bdsimmons** [comment]
@vincentwoo I would be happy to!

When you authenticate with a secret key on firebase, it basically totally disregards the security rules. In our case, every user has to be authenticated with a UID  to access their node under the users node, but if i need to write a script to manipulate many users, then i have to use secret key authentication. 

I did test if putting false under users for .read and .write would work, and sent a request to /users for our test firebase account, and it did indeed crash the firebase account. This addition is meant to give peace of mind when using secret key authentication that certain locations will never get a request sent to them.

**Comment by jwngr** [comment]
Vincent is correct here in that you should just use security rules to prevent access to certain nodes. Authenticating with a secret is generally regarded as a bad practice because it will cause you to skip all rules, including validate rules which enforce your schema. You should instead [mint a custom token](https://github.com/firebase/firebase-token-generator-ruby) for your server with a custom `uid`, write rules against that `uid`, and then authenticated with that custom token. This is a much safer option and gives you the intended behavior without any changes to this library. See [our custom authentication](https://www.firebase.com/docs/web/guide/login/custom.html) docs for more information.

**Comment by bdsimmons** [comment]
@jwngr. That seems better indeed. Thanks!

**Comment by bdsimmons** [comment]
I guess, if someone is going to use a secret token though, this is still a security feature. But I'll be making the change to use custom auth for us.

**Pull request closed without merging**
