### PR TITLE
Httpclient

### PR DESCRIPTION
**Pull request by aj0strow**
I think `httpclient` is the one. It's thread safe afaik:

```ruby
client = Firebase::Client.new(url, secret)
threads = 3.times.map do
  Thread.new{ client.get('test').body }
end
threads.each(&:join)
# doesnt blow up
```

Seems to be 2x faster than `patron`. Here's using the same [benchmark gist](https://gist.githubusercontent.com/aj0strow/699012f8014793190585/raw/819484c077bdd2e8a4246f40b155215d7d1919c8/bench.rb). 

Before with `typheous`:

```
       user     system      total        real
curl          0.000000   0.000000   0.050000 (  0.306820)
firebase gem  0.030000   0.010000   0.040000 (  1.302462)
patron        0.010000   0.000000   0.010000 (  0.508994)
```

After with `httpclient`:

```
       user     system      total        real
curl          0.000000   0.000000   0.050000 (  0.494802)
firebase gem  0.010000   0.000000   0.010000 (  0.248934)
patron        0.030000   0.010000   0.040000 (  0.461365)
```

Should close:

https://github.com/oscardelben/firebase-ruby/pull/35 https://github.com/oscardelben/firebase-ruby/issues/32 https://github.com/oscardelben/firebase-ruby/issues/31 maybe https://github.com/oscardelben/firebase-ruby/pull/33 ?

### CODE REVIEW

**Comment by oscardelben** [comment]
Hi all,

Sorry for the delay, I'll take a look at this very soon.

**Comment by vincentwoo** [comment]
@oscardelben ping

**Comment by vincentwoo** [comment]
Merged!

**Comment by aj0strow** [comment]
@vincentwoo the best, thank you

**Pull request closed without merging**
